In [32]:
import pandas as pd
import numpy as np

col_name = ['mpg','cylinders','displacement','horsepower','weight','acceleration','model year','origin','car name']

data = pd.read_csv('auto-mpg.data',  delimiter=r'\s+',names=col_name, index_col='car name')
data.replace('?', np.nan, inplace=True)
data.dropna(inplace=True)
data.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
car name,,,,,,,,
chevrolet chevelle malibu,18.0,8,307.0,130.0,3504.0,12.0,70,1
buick skylark 320,15.0,8,350.0,165.0,3693.0,11.5,70,1
plymouth satellite,18.0,8,318.0,150.0,3436.0,11.0,70,1
amc rebel sst,16.0,8,304.0,150.0,3433.0,12.0,70,1
ford torino,17.0,8,302.0,140.0,3449.0,10.5,70,1

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392 entries, chevrolet chevelle malibu to chevy s-10
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    object
 4   weight        392 non-null    float64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64
 7   origin        392 non-null    int64
dtypes: float64(4), int64(3), object(1)
memory usage: 27.6+ KB

In [34]:
data[['horsepower']]  = data[['horsepower']].astype(float)

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392 entries, chevrolet chevelle malibu to chevy s-10
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    float64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64
 7   origin        392 non-null    int64
dtypes: float64(5), int64(3)
memory usage: 27.6+ KB

In [36]:
X = data.drop('mpg', axis=1)
y = data.mpg

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=0, test_size=0.2)

In [38]:
from sklearn.metrics import mean_absolute_error
def getMEA(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    
    print(np.concatenate((pred.reshape(len(pred), 1), y_test.values.reshape(len(y_test), 1)),1))
    
    return mean_absolute_error(y_test, pred)

In [39]:
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()
print('MEA:', getMEA(model1, X_train, X_test, y_train, y_test))

[[25.95976758 28.        ]
 [25.60788501 22.3       ]
 [10.61225174 12.        ]
 [32.30352198 38.        ]
 [33.22766006 33.8       ]
 [23.48316108 19.4       ]
 [34.47461471 38.1       ]
 [25.99032589 30.        ]
 [20.50776441 20.        ]
 [27.05444489 20.        ]
 [27.75160936 27.        ]
 [13.69019408 16.5       ]
 [25.15139692 24.5       ]
 [ 8.72650431 11.        ]
 [16.70254202 16.9       ]
 [33.11103405 33.7       ]
 [25.80495335 21.6       ]
 [12.80029168 14.        ]
 [25.52325492 26.        ]
 [27.0886937  28.4       ]
 [20.84163971 13.        ]
 [18.01437486 16.        ]
 [23.98078035 20.        ]
 [27.03960846 25.        ]
 [31.56462442 41.5       ]
 [11.28411702 14.        ]
 [28.75120589 25.8       ]
 [25.7518709  25.1       ]
 [22.99602683 20.        ]
 [14.95184549 17.        ]
 [22.59174951 20.        ]
 [31.01448494 31.6       ]
 [24.01032178 22.        ]
 [28.21943285 26.        ]
 [21.88603845 21.        ]
 [29.44121304 29.8       ]
 [28.78928643 31.        ]
 [12.06170572 13.        ]
 [14.85723672 16.        ]
 [10.38298149 14.        ]
 [13.9746528  15.        ]
 [34.53168701 44.6       ]
 [30.78104988 31.3       ]
 [13.67225119 16.        ]
 [30.65909179 29.        ]
 [15.41205519 16.        ]
 [30.07959401 29.        ]
 [10.68953008 13.        ]
 [17.45681417 17.5       ]
 [22.22045797 18.        ]
 [26.64937081 26.        ]
 [15.16906123 15.        ]
 [ 8.72418947 10.        ]
 [23.35358172 22.        ]
 [31.3835003  34.3       ]
 [26.14099966 30.7       ]
 [26.17381276 20.2       ]
 [20.80790958 22.        ]
 [31.86518377 33.        ]
 [24.51926846 21.        ]
 [19.22697621 22.        ]
 [27.34483458 24.        ]
 [31.04997741 31.5       ]
 [10.40260623 15.        ]
 [25.8320082  26.        ]
 [16.93945957 16.        ]
 [10.40462155 14.        ]
 [29.22446655 27.        ]
 [21.0593497  25.        ]
 [33.44619615 40.8       ]
 [33.82786766 36.1       ]
 [29.21561393 30.        ]
 [20.23084747 17.6       ]
 [16.08827942 15.5       ]
 [21.03974269 23.        ]
 [12.85052556 14.        ]
 [25.80674676 26.        ]
 [21.38562128 19.2       ]
 [31.76028992 31.5       ]]
MEA: 2.3858493040095423

In [40]:
from sklearn.svm import SVR
model2 = SVR(kernel='rbf')
print('MEA:', getMEA(model2, X_train, X_test, y_train, y_test))

[[29.00026533 28.        ]
 [23.13478924 22.3       ]
 [13.65592203 12.        ]
 [28.99217091 38.        ]
 [28.86351289 33.8       ]
 [20.51385225 19.4       ]
 [30.01615786 38.1       ]
 [20.32928309 30.        ]
 [21.38291905 20.        ]
 [27.91534878 20.        ]
 [30.78794711 27.        ]
 [13.85531536 16.5       ]
 [24.31852802 24.5       ]
 [12.99386261 11.        ]
 [13.92351126 16.9       ]
 [28.40183628 33.7       ]
 [23.90027205 21.6       ]
 [14.99871227 14.        ]
 [28.01342527 26.        ]
 [24.87398734 28.4       ]
 [20.72241097 13.        ]
 [17.49570914 16.        ]
 [26.91667222 20.        ]
 [22.63391327 25.        ]
 [28.86457341 41.5       ]
 [14.42885449 14.        ]
 [25.26205995 25.8       ]
 [24.49114276 25.1       ]
 [22.82344493 20.        ]
 [17.17536237 17.        ]
 [23.75702206 20.        ]
 [25.19702576 31.6       ]
 [26.16115117 22.        ]
 [30.05181371 26.        ]
 [21.82788599 21.        ]
 [24.56908419 29.8       ]
 [31.1378182  31.        ]
 [13.61325905 13.        ]
 [14.53116741 16.        ]
 [13.86800621 14.        ]
 [16.99544215 15.        ]
 [30.70237542 44.6       ]
 [25.92420372 31.3       ]
 [14.74341514 16.        ]
 [30.168821   29.        ]
 [14.00155312 16.        ]
 [26.03376344 29.        ]
 [13.19499086 13.        ]
 [15.97485752 17.5       ]
 [23.82119251 18.        ]
 [28.13756852 26.        ]
 [17.78811893 15.        ]
 [13.8893281  10.        ]
 [26.92640702 22.        ]
 [28.56357728 34.3       ]
 [21.01081441 30.7       ]
 [21.71432368 20.2       ]
 [19.41875576 22.        ]
 [31.00937952 33.        ]
 [28.26637367 21.        ]
 [23.51364023 22.        ]
 [29.1137187  24.        ]
 [29.8752101  31.5       ]
 [13.92313869 15.        ]
 [28.56116758 26.        ]
 [15.95738898 16.        ]
 [14.00441508 14.        ]
 [25.15915557 27.        ]
 [24.90721507 25.        ]
 [29.1114778  40.8       ]
 [30.97996778 36.1       ]
 [28.79374281 30.        ]
 [16.86558209 17.6       ]
 [14.73287714 15.5       ]
 [22.94717003 23.        ]
 [14.74944747 14.        ]
 [30.08728807 26.        ]
 [18.82020032 19.2       ]
 [29.52103425 31.5       ]]
MEA: 3.2047193914686587

In [41]:
from sklearn.tree import DecisionTreeRegressor
model3 = DecisionTreeRegressor(random_state=0)
print('MEA:', getMEA(model3, X_train, X_test, y_train, y_test))

[[28.  28. ]
 [26.4 22.3]
 [13.  12. ]
 [38.  38. ]
 [36.  33.8]
 [19.  19.4]
 [32.  38.1]
 [43.4 30. ]
 [18.  20. ]
 [28.  20. ]
 [26.  27. ]
 [16.  16.5]
 [25.5 24.5]
 [14.  11. ]
 [15.5 16.9]
 [33.  33.7]
 [23.2 21.6]
 [15.  14. ]
 [28.  26. ]
 [28.  28.4]
 [18.  13. ]
 [15.  16. ]
 [21.  20. ]
 [19.8 25. ]
 [32.2 41.5]
 [13.  14. ]
 [26.  25.8]
 [23.8 25.1]
 [19.  20. ]
 [14.  17. ]
 [17.  20. ]
 [32.9 31.6]
 [23.  22. ]
 [31.  26. ]
 [19.  21. ]
 [32.  29.8]
 [35.  31. ]
 [14.  13. ]
 [16.  16. ]
 [15.  14. ]
 [13.  15. ]
 [36.1 44.6]
 [32.4 31.3]
 [15.  16. ]
 [30.  29. ]
 [15.5 16. ]
 [31.  29. ]
 [14.  13. ]
 [19.4 17.5]
 [18.  18. ]
 [24.  26. ]
 [14.  15. ]
 [ 9.  10. ]
 [24.  22. ]
 [27.2 34.3]
 [23.9 30.7]
 [38.  20.2]
 [18.1 22. ]
 [33.  33. ]
 [23.  21. ]
 [18.  22. ]
 [28.  24. ]
 [29.5 31.5]
 [14.  15. ]
 [30.  26. ]
 [17.  16. ]
 [15.  14. ]
 [28.  27. ]
 [20.  25. ]
 [46.6 40.8]
 [32.  36.1]
 [29.5 30. ]
 [18.2 17.6]
 [17.5 15.5]
 [18.  23. ]
 [15.  14. ]
 [29.  26. ]
 [19.4 19.2]
 [30.  31.5]]
MEA: 2.627848101265822

In [42]:
from sklearn.ensemble import RandomForestRegressor
model4 = RandomForestRegressor(n_estimators=40)
print('MEA:', getMEA(model4, X_train, X_test, y_train, y_test))

[[27.5625 28.    ]
 [26.0375 22.3   ]
 [13.425  12.    ]
 [34.8175 38.    ]
 [36.3775 33.8   ]
 [20.285  19.4   ]
 [36.77   38.1   ]
 [32.365  30.    ]
 [18.7925 20.    ]
 [25.5    20.    ]
 [28.975  27.    ]
 [13.725  16.5   ]
 [24.12   24.5   ]
 [12.625  11.    ]
 [15.9475 16.9   ]
 [34.35   33.7   ]
 [22.3175 21.6   ]
 [14.675  14.    ]
 [26.6375 26.    ]
 [28.0225 28.4   ]
 [18.295  13.    ]
 [16.23   16.    ]
 [21.8    20.    ]
 [23.8175 25.    ]
 [34.66   41.5   ]
 [13.4    14.    ]
 [27.8425 25.8   ]
 [24.31   25.1   ]
 [19.2    20.    ]
 [14.8375 17.    ]
 [20.045  20.    ]
 [31.4325 31.6   ]
 [23.2225 22.    ]
 [30.4    26.    ]
 [18.7475 21.    ]
 [30.02   29.8   ]
 [32.9125 31.    ]
 [13.9375 13.    ]
 [14.7375 16.    ]
 [13.975  14.    ]
 [13.7625 15.    ]
 [34.16   44.6   ]
 [31.4625 31.3   ]
 [14.3    16.    ]
 [30.5    29.    ]
 [15.35   16.    ]
 [29.4575 29.    ]
 [13.55   13.    ]
 [16.19   17.5   ]
 [19.2175 18.    ]
 [25.6175 26.    ]
 [14.9675 15.    ]
 [11.2    10.    ]
 [22.8375 22.    ]
 [33.5825 34.3   ]
 [25.155  30.7   ]
 [21.6075 20.2   ]
 [19.0325 22.    ]
 [32.55   33.    ]
 [24.1125 21.    ]
 [19.415  22.    ]
 [28.3375 24.    ]
 [32.1925 31.5   ]
 [13.4875 15.    ]
 [26.7575 26.    ]
 [16.425  16.    ]
 [14.2    14.    ]
 [29.695  27.    ]
 [23.22   25.    ]
 [39.985  40.8   ]
 [34.1125 36.1   ]
 [31.39   30.    ]
 [18.795  17.6   ]
 [15.5675 15.5   ]
 [18.8975 23.    ]
 [14.1125 14.    ]
 [29.25   26.    ]
 [18.565  19.2   ]
 [31.     31.5   ]]
MEA: 1.67743670886076