In [30]:
col_name = ['Sex', 'Length', 'Diameter', 'Height', 'Whole_weight', 'Shucked_weight', 'Viscera_weight', 'Shell_weight', 'Rings']

In [31]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
data = pd.read_csv('abalone.data', names=col_name)
data

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [32]:
data.isnull().sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole_weight      0
Shucked_weight    0
Viscera_weight    0
Shell_weight      0
Rings             0
dtype: int64

In [33]:
X = data.drop('Rings', axis=1)
y = data.Rings

In [34]:
from sklearn.preprocessing import OneHotEncoder
encode = OneHotEncoder(handle_unknown='ignore', sparse=False)
sex_transform_df = pd.DataFrame(encode.fit_transform(X[['Sex']]), columns=encode.get_feature_names_out(['Sex']))
sex_transform_df


X = pd.concat([X, sex_transform_df], axis=1)
X.drop('Sex', axis=1, inplace=True)
X

C:\Users\DELL INSPIRON 5625\AppData\Roaming\Python\Python311\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Sex_F,Sex_I,Sex_M
0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,0.0,0.0,1.0
1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,0.0,0.0,1.0
2,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,1.0,0.0,0.0
3,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,0.0,0.0,1.0
4,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
4172,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,1.0,0.0,0.0
4173,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,0.0,0.0,1.0
4174,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,0.0,0.0,1.0
4175,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,1.0,0.0,0.0
4176,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,0.0,0.0,1.0

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.2)

In [36]:
y_test

668     13
1580     8
3784    11
463      5
2615    12
        ..
575     11
3231    12
1084     7
290     17
2713     4
Name: Rings, Length: 836, dtype: int64

In [37]:
X_train

,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Sex_F,Sex_I,Sex_M
3141,0.180,0.135,0.080,0.0330,0.0145,0.0070,0.0100,0.0,1.0,0.0
3521,0.215,0.150,0.055,0.0410,0.0150,0.0090,0.0125,0.0,1.0,0.0
883,0.660,0.530,0.170,1.3905,0.5905,0.2120,0.4530,0.0,0.0,1.0
3627,0.715,0.525,0.200,1.8900,0.9500,0.4360,0.4305,0.0,0.0,1.0
2106,0.595,0.455,0.155,1.0410,0.4160,0.2105,0.3650,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
1033,0.650,0.525,0.185,1.6220,0.6645,0.3225,0.4770,0.0,0.0,1.0
3264,0.655,0.500,0.140,1.1705,0.5405,0.3175,0.2850,1.0,0.0,0.0
1653,0.595,0.450,0.145,0.9590,0.4630,0.2065,0.2535,0.0,0.0,1.0
2607,0.625,0.490,0.165,1.1270,0.4770,0.2365,0.3185,1.0,0.0,0.0
2732,0.410,0.325,0.110,0.3260,0.1325,0.0750,0.1010,0.0,1.0,0.0

In [38]:
from sklearn.metrics import mean_absolute_error
def getMEA(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_pred = y_pred.round().astype(int)
    return mean_absolute_error(y_test, y_pred)

In [39]:
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()
print("MEA Random Fores:", getMEA(model1, X_train, X_test, y_train, y_test))

MEA Random Fores: 1.5454545454545454

In [40]:
from sklearn.svm import SVR
model2 = SVR(kernel='rbf')
print("MEA Random Fores:", getMEA(model2, X_train, X_test, y_train, y_test))

MEA Random Fores: 1.5

In [41]:
from sklearn.tree import DecisionTreeRegressor
model3 = DecisionTreeRegressor()
print("MEA Random Fores:", getMEA(model3, X_train, X_test, y_train, y_test))

MEA Random Fores: 2.062200956937799

In [42]:
from sklearn.ensemble import RandomForestRegressor
model4 = RandomForestRegressor(random_state=0)
print("MEA Random Fores:", getMEA(model4, X_train, X_test, y_train, y_test))

MEA Random Fores: 1.5227272727272727